version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'conduit'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: trust
    user: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi_development:
    build:
      target: development
    tty: true
    stdin_open: true
    restart: always
    command: uvicorn main:app --host=0.0.0.0 --reload
    ports:
      - 8000:8000
    volumes:
      - ./:/server
    depends_on:
      - postgres

volumes:
  db_data:
